CREATE TABLE IF NOT EXISTS USERS(
	ID 		        INTEGER		NOT NULL,
	USERNAME	    TEXT		NOT NULL	UNIQUE,
	PASSWORD	    TEXT		NOT NULL,
	FIRSTNAME 	    TEXT		NOT NULL,
	LASTNAME	    TEXT		NOT NULL,
	MIDDLENAME   	TEXT,
	PHONE_NUMBER	TEXT		NOT NULL,
	EMAIL		    TEXT		NOT NULL,
	PRIMARY KEY (ID)
);
CREATE SEQUENCE IF NOT EXISTS USERS_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;

CREATE TABLE IF NOT EXISTS CLIENTS(
	ID 		        INTEGER		NOT NULL,
	FIRSTNAME 	    TEXT		NOT NULL,
	LASTNAME	    TEXT		NOT NULL,
	MIDDLENAME   	TEXT,
	PARTNER_CODE	INTEGER		NOT NULL	UNIQUE,
	PRIMARY KEY (ID)
);
CREATE SEQUENCE IF NOT EXISTS CLIENTS_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;

CREATE TABLE IF NOT EXISTS CONTRACTS(
	ID 			            INTEGER		NOT NULL,
    USER_ID                 INTEGER     NOT NULL,
    CLIENT_ID               INTEGER     NOT NULL,
    ADDENDUM_NUMBER 	    INTEGER		NOT NULL	UNIQUE,
	PRODUCT 		        TEXT		NOT NULL,
	EXPIRATION_DATE         DATE		NOT NULL,
	COST			        BIGINT		NOT NULL,
	DATE_OF_NEXT_PAYMENT	DATE,
	PRIMARY KEY (ID),

    UNIQUE (USER_ID, ADDENDUM_NUMBER),
    UNIQUE (CLIENT_ID, ADDENDUM_NUMBER),

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
);
CREATE SEQUENCE IF NOT EXISTS CONTRACTS_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;

CREATE TABLE IF NOT EXISTS CLIENT_PHONE_NUMBER(
	CLIENT_ID	    INTEGER		NOT NULL,
	PHONE_NUMBER	TEXT		NOT NULL,

	UNIQUE (CLIENT_ID, PHONE_NUMBER),

	FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
);